# Generated by Django 3.1.12 on 2025-05-29 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blok',
            fields=[
                ('blok_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('blok_adi', models.CharField(max_length=20)),
                ('blok_onceligi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bolum',
            fields=[
                ('bolum_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('bolum_adi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ders',
            fields=[
                ('ders_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ders_kodu', models.CharField(max_length=20)),
                ('ders_adi', models.CharField(max_length=50)),
                ('ders_turu', models.CharField(choices=[('teorik', 'Teorik'), ('uygulama', 'Uygulama'), ('laboratuvar', 'Laboratuvar'), ('online', 'Online')], max_length=20)),
                ('ogrenci_sayisi', models.IntegerField()),
                ('oncelik_numarasi', models.IntegerField(default=3)),
                ('ders_zamani', models.CharField(blank=True, max_length=20, null=True)),
                ('ders_uzunlugu', models.IntegerField(default=1)),
                ('engelli_erişim_gerektiriyor', models.BooleanField(default=False)),
                ('uygulama_lab_gerekli', models.BooleanField(default=False)),
                ('sinif', models.IntegerField(choices=[(1, '1. Sınıf'), (2, '2. Sınıf'), (3, '3. Sınıf'), (4, '4. Sınıf')], default=1)),
                ('bolum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ders_programi.bolum')),
            ],
        ),
        migrations.CreateModel(
            name='Derslik',
            fields=[
                ('derslik_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('kod', models.CharField(max_length=20)),
                ('kapasite', models.IntegerField()),
                ('erisilebilirlik', models.BooleanField(default=False)),
                ('oncelik', models.IntegerField()),
                ('tur', models.CharField(choices=[('teorik', 'Teorik'), ('laboratuvar', 'Laboratuvar'), ('uygulama', 'Uygulama')], max_length=20)),
                ('laboratuvar_uygunlugu', models.BooleanField(default=False)),
                ('blok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ders_programi.blok')),
            ],
        ),
        migrations.CreateModel(
            name='Kullanici',
            fields=[
                ('kullanici_id', models.AutoField(primary_key=True, serialize=False)),
                ('isim', models.CharField(max_length=50)),
                ('isim2', models.CharField(blank=True, max_length=50, null=True)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('parola', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('ogretim_uyesi', 'Öğretim Üyesi'), ('editor', 'Editör'), ('asistan', 'Asistan')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Zaman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gun', models.CharField(max_length=10)),
                ('saat', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='OzelDurum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gun', models.CharField(max_length=10)),
                ('saat', models.CharField(max_length=5)),
                ('aciklama', models.CharField(blank=True, max_length=200, null=True)),
                ('ders', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ders_programi.ders')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ders_programi.kullanici')),
            ],
        ),
        migrations.CreateModel(
            name='DersProgrami',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=5)),
                ('date', models.CharField(max_length=10)),
                ('bolum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ders_programi.bolum')),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ders_programi.ders')),
                ('derslik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ders_programi.derslik')),
                ('sorumlu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ders_programi.kullanici')),
            ],
        ),
        migrations.AddField(
            model_name='ders',
            name='ogretmen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verdigi_dersler', to='ders_programi.kullanici'),
        ),
        migrations.AddField(
            model_name='blok',
            name='bolum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloklar', to='ders_programi.bolum'),
        ),
    ]
